version: '3'
services:
    m_web:
        image:  ubuntu-nginx-php74
        container_name: m_web
        ports:
          - "80:80"
        volumes:
          - /c/Users/sanjb/Documents/magento_2_source:/var/www/html
          - /c/Users/sanjb/Documents/magento_2_source/sites-available:/etc/nginx/sites-available
          #- /c/Users/sanjb/Documents/magento_2_source/sites-available:/etc/nginx/sites-enabled
        ports:
          - "80:80"
        links:
          - magento_ce_db
          - elasticsearch
        depends_on:
          - magento_ce_db
          - elasticsearch   

        # image: nginx-php74  
        # container_name: web
        # restart: always
        # ports:
         # - "80:80"
        # volumes:
            # - ./code:/code
            # - ./site.conf:/etc/nginx/conf.d/site.conf
    magento_ce_db:
        image: mysql:8.0
        container_name: magento_ce_db
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - db-data-test:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
        ports:
          - "8080:80"
        links:
          - magento_ce_db:db
        depends_on:
          - magento_ce_db
    elasticsearch:
        image: elasticsearch:7.9.3
        container_name: elasticsearch_7_9
        restart: always
        
        environment:
           - "discovery.type=single-node"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - data01:/usr/share/elasticsearch/data
        ports:
          - 9200:9200

volumes:
    db-data-test:
        driver: local
    data01:
        driver: local